<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class EntrepotSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('entrepots')->insert([
            [                'nom' => 'entrepot1',

                'adresse' => 'Zone Industrielle Charguia 1, Tunis',
                'capacite_totale' => 10000,
                'capacite_disponible' => 7800,
                'statut' => 'ACTIF',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [             'nom' => 'entrepot2',
                'adresse' => 'Route de Sfax Km 5, Sousse',
                'capacite_totale' => 8000,
                'capacite_disponible' => 5200,
                'statut' => 'ACTIF',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [          'nom' => 'entrepot3',
                'adresse' => 'Zone Industrielle Thyna, Sfax',
                'capacite_totale' => 9000,
                'capacite_disponible' => 6100,
                'statut' => 'ACTIF',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [           'nom' => 'entrepot4',
                'adresse' => 'Zone Portuaire, Bizerte',
                'capacite_totale' => 7000,
                'capacite_disponible' => 4300,
                'statut' => 'ACTIF',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [         'nom' => 'entrepot5',
                'adresse' => 'Zone Industrielle, Gabès',
                'capacite_totale' => 6000,
                'capacite_disponible' => 1500,
                'statut' => 'INACTIF',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nom' => 'entrepot6',
                'adresse' => 'Parc Industriel, Monastir',
                'capacite_totale' => 5000,
                'capacite_disponible' => 2600,
                'statut' => 'ACTIF',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [             'nom' => 'entrepot7',
                'adresse' => 'Zone Agricole, Kairouan',
                'capacite_totale' => 4000,
                'capacite_disponible' => 2100,
                'statut' => 'ACTIF',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [          'nom' => 'entrepot8',
                'adresse' => 'Route Nationale 1, Nabeul',
                'capacite_totale' => 6500,
                'capacite_disponible' => 3000,
                'statut' => 'ACTIF',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [       'nom' => 'entrepot9',
                'adresse' => 'El Ghazala Technopark, Ariana',
                'capacite_totale' => 7500,
                'capacite_disponible' => 4100,
                'statut' => 'ACTIF',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [          'nom' => 'entrepot10',
                'adresse' => 'Zone Logistique Sud, Médenine',
                'capacite_totale' => 5500,
                'capacite_disponible' => 2800,
                'statut' => 'ACTIF',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}