type AuthPayload {
    token: String!
    user: User!
}

extend type Query {
    me: User
        @field(resolver: "App\\GraphQL\\Resolvers\\UserResolver@me")
        @guard
}

extend type Mutation {
    login(
        email: String!
        password: String!
    ): AuthPayload
        @field(resolver: "App\\GraphQL\\Mutations\\Auth\\AuthMutator@login")

    register(
        name: String!
        email: String!
        password: String!
        role: String
    ): AuthPayload
        @field(resolver: "App\\GraphQL\\Mutations\\Auth\\AuthMutator@register")

    resendVerificationEmail: String
        @field(resolver: "App\\GraphQL\\Mutations\\Auth\\AuthMutator@resendVerificationEmail")
        @auth

    verifyEmail(token: String!): String!
        @field(resolver: "App\\GraphQL\\Mutations\\Auth\\AuthMutator@verifyEmail")

    logout: Boolean
        @field(resolver: "App\\GraphQL\\Mutations\\Auth\\AuthMutator@logout")
        @auth

    forgotPassword(email: String!): String!
        @field(resolver: "App\\GraphQL\\Mutations\\Auth\\AuthMutator@forgotPassword")

    resetPassword(
        email: String!
        token: String!
        password: String!
        password_confirmation: String!
    ): String!
        @field(resolver: "App\\GraphQL\\Mutations\\Auth\\AuthMutator@resetPassword")
}