type User {
    id: ID!
    name: String!
    first_name: String
    last_name: String
    email: String!
    email_verified_at: DateTime
    role: String!
    phone: String
    birth_date: Date
    address: String
    is_active: Boolean
    last_login_at: DateTime
}

extend type Query {
    users: [User!]!
        @field(resolver: "App\\GraphQL\\Queries\\UserAdminQuery@users")
        @guard(with: ["api"])

    user(id: ID!): User
        @find
        @guard(with: ["api"])
}

extend type Mutation {
    updateUserRole(id: ID!, role: String!): User!
        @field(resolver: "App\\GraphQL\\Mutations\\Admin\\UserAdminMutator@updateUserRole")
        @guard(with: ["api"])

    updateUserStatus(id: ID!, is_active: Boolean!): User!
        @field(resolver: "App\\GraphQL\\Mutations\\Admin\\UserAdminMutator@updateUserStatus")
        @guard(with: ["api"])
}