type Entrepot {
  id: ID!
  nom: String!
  adresse: String
  capacite_totale: Float
  stock_existant: Float
  capacite_disponible: Float
  statut: String

  entrepotLots: [EntrepotLot!]! @hasMany

  created_at: DateTime
  updated_at: DateTime
}

type EntrepotLot {
  id: ID!
  quantite: Float!

  entrepot: Entrepot! @belongsTo
  lot: Lot @belongsTo
  emballage: Emballage! @belongsTo

  created_at: DateTime
  updated_at: DateTime
}

input CreateEntrepotInput {
  nom: String!
  adresse: String
  capacite_totale: Float!
  statut: String
}

input UpdateEntrepotInput {
  id: ID!
  nom: String
  adresse: String
  capacite_totale: Float
  statut: String
}

extend type Query {
  entrepots: [Entrepot!]!
    @all(model: "App\\Models\\Entrepot")

  entrepot(id: ID! @eq): Entrepot
    @find(model: "App\\Models\\Entrepot")
}

extend type Mutation {
  createEntrepot(input: CreateEntrepotInput!): Entrepot
    @field(resolver: "App\\GraphQL\\Mutations\\EntrepotMutator@create")

  updateEntrepot(input: UpdateEntrepotInput!): Entrepot
    @field(resolver: "App\\GraphQL\\Mutations\\EntrepotMutator@update")

  deleteEntrepot(id: ID!): Boolean
    @delete(model: "App\\Models\\Entrepot")
}