<?php

namespace App\Enums;

class AlertType
{
    public const LOW_STOCK = 'LOW_STOCK';
    public const LOT_EXPIRING = 'LOT_EXPIRING';
    public const CONTRAT_EXPIRING = 'CONTRAT_EXPIRING';
    public const SUPPLIER_DELAY = 'SUPPLIER_DELAY';
    public const INVENTORY_ANOMALY = 'INVENTORY_ANOMALY';
    public const WAREHOUSE_CAPACITY_HIGH = 'WAREHOUSE_CAPACITY_HIGH';
    public const DELIVERY_IMMINENT = 'DELIVERY_IMMINENT';

    public const CONTRACT_EXPIRED = 'CONTRACT_EXPIRED';
    public const CONTRACT_CONSUMPTION_HIGH = 'CONTRACT_CONSUMPTION_HIGH';
    public const CONTRACT_QUANTITY_EXCEEDED = 'CONTRACT_QUANTITY_EXCEEDED';
    public const ORDER_NOT_RECEIVED_ON_TIME = 'ORDER_NOT_RECEIVED_ON_TIME';
}